# Generated by Django 5.2.1 on 2025-05-14 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, unique=True, verbose_name='Nome')),
                ('start_project', models.DateField(blank=True, null=True, verbose_name='Início do projeto')),
                ('start_work', models.DateField(blank=True, null=True, verbose_name='Início da obra')),
                ('end_project', models.DateField(blank=True, null=True, verbose_name='Fim de projeto/obra')),
                ('parcel', models.PositiveIntegerField(default=1, verbose_name='Parcelas')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.modelclient', verbose_name='Cliente')),
            ],
        ),
    ]
