# Generated by Django 5.2.1 on 2026-01-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproject',
            name='description',
            field=models.TextField(default=1, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
