# Generated by Django 5.2.1 on 2026-01-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_modelproject_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('COR', 'Corrido'), ('CONT', 'Contratado')], default='COR', verbose_name='Tipo de Serviço')),
                ('description', models.TextField(verbose_name='Descriçao do serviço')),
                ('closing', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('last_changes', models.DateField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_projects', to='projects.modelproject', verbose_name='Projeto')),
            ],
        ),
    ]
