# Generated by Django 5.2.1 on 2026-01-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelservice',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado'), ('APROV', 'Aprovado'), ('CANC', 'Cancelado')], default='OPEN', verbose_name='Status'),
        ),
    ]
