# Generated by Django 5.2.1 on 2026-01-22 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_modelservice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelservice',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado'), ('APROV', 'Aprovado'), ('WIP', 'Em Andamento'), ('CANC', 'Cancelado'), ('WAR', 'Garantia')], default='OPEN', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ModelDisplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Partida')),
                ('arrive_time', models.TimeField(blank=True, null=True, verbose_name='Chegada')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deslocamentos', to='services.modelservice', verbose_name='Serviço')),
            ],
        ),
    ]
