# Generated by Django 5.2.1 on 2026-01-23 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_modelservice_status_modeldisplacement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeldisplacement',
            options={'verbose_name': 'Deslocamento'},
        ),
        migrations.AlterField(
            model_name='modeldisplacement',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displacements', to='services.modelservice', verbose_name='Serviço'),
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('completa', models.BooleanField(default=False, verbose_name='Completa')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('tarefa_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='services.tarefa', verbose_name='Tarefa Pai')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['criada_em'],
            },
        ),
    ]
