# Generated by Django 5.2.1 on 2026-01-23 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_modeldisplacement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.modelservice'),
            preserve_default=False,
        ),
    ]
