# Generated by Django 5.2.1 on 2026-01-23 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_tarefa_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='services.modelservice', verbose_name='Serviço'),
        ),
    ]
