# Generated by Django 5.2.1 on 2026-01-23 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_tarefa_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelservice',
            old_name='last_changes',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='ModelTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('completed', models.BooleanField(default=False, verbose_name='Completa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='services.modeltask', verbose_name='Tarefa Pai')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='services.modelservice', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
