# Generated by Django 5.2.1 on 2026-01-23 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_modelproject_description'),
        ('services', '0007_rename_last_changes_modelservice_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltask',
            name='service',
        ),
        migrations.AddField(
            model_name='modeltask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completada em'),
        ),
        migrations.AddField(
            model_name='modeltask',
            name='completed_in_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_completed', to='services.modelservice', verbose_name='Completada no Serviço'),
        ),
        migrations.AddField(
            model_name='modeltask',
            name='created_in_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to='services.modelservice', verbose_name='Criada no Serviço'),
        ),
        migrations.AddField(
            model_name='modeltask',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.modelproject', verbose_name='Projeto'),
            preserve_default=False,
        ),
    ]
