# Generated by Django 5.2.1 on 2026-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_modeltask_service_modeltask_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelservice',
            name='date',
            field=models.DateField(),
        ),
    ]
