# Generated by Django 5.2.1 on 2026-01-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_modelclient_project_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelclient',
            name='project_prefix',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Prefixo de projeto'),
        ),
    ]
