# Generated by Django 5.2.1 on 2025-05-14 23:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutflowTypeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModelOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=50, verbose_name='Despesa')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('payment_method', models.CharField(choices=[('PIX', 'PIX'), ('DEB', 'Cartão de débito'), ('REF', 'Reembolso')], default='PIX', verbose_name='Método de pagamento')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('favored', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outflow', to='supplier.modelsupplier', verbose_name='Favorecido')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outflow', to='projects.modelproject', verbose_name='Projeto')),
                ('type', models.ManyToManyField(blank=True, related_name='outflows', to='outflows.outflowtypechoice', verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCreditOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=50, verbose_name='Despesa')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('closing', models.BooleanField(default=False, verbose_name='Fechamento')),
                ('favored', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit', to='supplier.modelsupplier', verbose_name='Favorecido')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit', to='projects.modelproject', verbose_name='Projeto')),
                ('type', models.ManyToManyField(blank=True, related_name='credit', to='outflows.outflowtypechoice', verbose_name='Tipo')),
            ],
        ),
    ]
