# Generated by Django 5.2.1 on 2025-05-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloutflow',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'PIX'), ('DEB', 'Cartão de débito'), ('REF', 'Reembolso'), ('AUT', 'Débito Automático'), ('BOL', 'Boleto')], default='PIX', verbose_name='Método de pagamento'),
        ),
    ]
