# Generated by Django 5.2.1 on 2025-05-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_alter_modeloutflow_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloutflow',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
