# Generated by Django 5.2.1 on 2025-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0003_modeloutflow_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcreditoutflow',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
