# Generated by Django 5.2.1 on 2026-01-26 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0004_modelcreditoutflow_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcreditoutflow',
            name='closing_outflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing_outflow', to='outflows.modeloutflow', verbose_name='Fechada em saída'),
        ),
    ]
