# Generated by Django 5.2.1 on 2025-05-14 23:00

import localflavor.br.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Nome')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR', verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Endereço')),
                ('neighborhood', models.CharField(blank=True, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, null=True, verbose_name='Cidade')),
                ('state', localflavor.br.models.BRStateField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep', localflavor.br.models.BRPostalCodeField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('cnpj', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
            ],
        ),
    ]
