# Generated by Django 5.2.1 on 2025-05-14 23:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.CharField(max_length=15, unique=True, verbose_name='Receita')),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('due_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('payment_method', models.CharField(choices=[('PIX', 'PIX'), ('CRED', 'Cartão de crédito'), ('DEB', 'Cartão de débito'), ('BOL', 'Boleto'), ('AUT', 'Débito Automático')], default='PIX', verbose_name='Método de pagamento')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inflows', to='projects.modelproject', verbose_name='Projeto')),
            ],
        ),
    ]
