# Generated by Django 5.2.1 on 2025-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0002_alter_modelinflow_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinflow',
            name='refund',
            field=models.BooleanField(default=False, verbose_name='Reembolso'),
        ),
    ]
