# Generated by Django 5.2.1 on 2025-05-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0003_modelinflow_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinflow',
            name='income',
            field=models.CharField(max_length=15, verbose_name='Receita'),
        ),
    ]
