# Generated by Django 5.2.1 on 2025-12-23 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0004_alter_modelinflow_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinflow',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data pagamento'),
        ),
        migrations.AlterField(
            model_name='modelinflow',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data vencimento'),
        ),
    ]
