# Generated by Django 5.2.1 on 2025-05-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0003_modelinflow_balance'),
        ('inflows', '0004_alter_modelinflow_income'),
    ]

    operations = [
    ]
