# Generated by Django 5.2.1 on 2026-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0005_modelinflow_paid_date_alter_modelinflow_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinflow',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'PIX'), ('CRED', 'Cartão de crédito'), ('DEB', 'Cartão de débito'), ('BOL', 'Boleto'), ('MON', 'Espécie')], default='PIX', verbose_name='Método de pagamento'),
        ),
    ]
